#!/bin/bash

name=`git symbolic-ref --short -q HEAD`

if [[ $2 != 'merge' ]]; then

	pattern='^(feature|bugfix)/([0-9]+)-(.*)'

	if [[ $name =~ $pattern ]]; then

		storyId=${BASH_REMATCH[2]}

		original=$(cat "$1")
		contentPattern='\[DEVJIRA-[0-9]+\]'
		# check if there already is the story number in commit message
		if [[ $original =~ $contentPattern ]]; then
			dummy=''
		else
			printf "[DEVJIRA-"$storyId"]\n$original" > "$1"
		fi
	fi
fi

# vim: set ft=zsh:
